# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import GroupShuffleSplit
# from sklearn.metrics import ndcg_score
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# import xgboost as xgb
# import lightgbm as lgb
# 
# st.set_page_config(page_title="LTR Search", page_icon="🔍", layout="wide")
# 
# st.markdown("""
# <style>
#   .result-card {
#       background: #1e1e1e; border: 1px solid #333; border-radius: 8px;
#       padding: 1rem 1.5rem; margin-bottom: 0.75rem;
#   }
#   .rank-badge { font-size: 1.4rem; font-weight: bold; color: #00d4aa; }
#   .product-id { font-family: monospace; color: #aaa; font-size: 0.85rem; }
#   .relevance-label { font-size: 0.8rem; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
#   .rel-3 { background: #00d4aa33; color: #00d4aa; }
#   .rel-2 { background: #4a9eff33; color: #4a9eff; }
#   .rel-1 { background: #ffa50033; color: #ffa500; }
#   .rel-0 { background: #ff444433; color: #ff4444; }
#   .matched-query { background: #00d4aa11; border-left: 3px solid #00d4aa;
#                    padding: 0.5rem 1rem; border-radius: 4px; margin-bottom: 1rem; }
# </style>
# """, unsafe_allow_html=True)
# 
# 
# @st.cache_resource
# def load_and_train():
#     QUERY = "query_id"
#     DOC   = "product_id"
# 
#     df = pd.read_parquet("https://data.vespa-cloud.com/sample-apps-data/product_ranking_train.parquet")
# 
#     esci_map    = {"E": 3, "S": 2, "C": 1, "I": 0}
#     esci_labels = {0: "Irrelevant", 1: "Complement", 2: "Substitute", 3: "Exact Match"}
#     df["relevance"]       = df["esci_label"].map(esci_map)
#     df["relevance_label"] = df["relevance"].map(esci_labels)
#     LABEL = "relevance"
# 
#     df = df.dropna(subset=[LABEL]).copy()
# 
#     non_feature = {LABEL, QUERY, DOC, "example_id", "query",
#                    "product_locale", "esci_label", "relevance_label",
#                    "small_version", "large_version", "split"}
#     feat_cols = [c for c in df.columns
#                  if c not in non_feature and pd.api.types.is_numeric_dtype(df[c])]
# 
#     for col in feat_cols:
#         df[col].fillna(df[col].median(), inplace=True)
# 
#     df = df.sort_values(QUERY).reset_index(drop=True)
# 
#     # ── Build query lookup + TF-IDF index for fuzzy search ───────────────
#     query_map = df.groupby("query_id")["query"].first().reset_index()
#     # query_map: dataframe with columns [query_id, query]
# 
#     vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1)
#     tfidf_matrix = vectorizer.fit_transform(query_map["query"].tolist())
# 
#     # ── Train/test split ──────────────────────────────────────────────────
#     splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
#     train_idx, test_idx = next(splitter.split(df, groups=df[QUERY].values))
#     train_df = df.iloc[train_idx].sort_values(QUERY).reset_index(drop=True)
#     test_df  = df.iloc[test_idx].sort_values(QUERY).reset_index(drop=True)
# 
#     X_tr, y_tr = train_df[feat_cols].values, train_df[LABEL].values
#     X_te, y_te = test_df[feat_cols].values,  test_df[LABEL].values
#     g_tr = train_df.groupby(QUERY, sort=False).size().values
#     g_te = test_df.groupby(QUERY, sort=False).size().values
# 
#     xgb_m = xgb.XGBRanker(objective="rank:ndcg", n_estimators=300,
#                            learning_rate=0.05, max_depth=6, verbosity=0)
#     xgb_m.fit(X_tr, y_tr, group=g_tr, eval_set=[(X_te, y_te)],
#               eval_group=[g_te], verbose=False)
# 
#     lgb_m = lgb.LGBMRanker(objective="lambdarank", n_estimators=300,
#                             learning_rate=0.05, num_leaves=63, verbose=-1,
#                             label_gain=[0, 1, 3, 7, 15])
#     lgb_m.fit(X_tr, y_tr.astype(int), group=g_tr,
#               eval_set=[(X_te, y_te.astype(int))], eval_group=[g_te])
# 
#     return df, feat_cols, xgb_m, lgb_m, query_map, vectorizer, tfidf_matrix
# 
# 
# def find_best_matching_query(user_text, vectorizer, tfidf_matrix, query_map, top_n=5):
#     """
#     Convert user's free text into TF-IDF vector,
#     find the most similar queries in the dataset via cosine similarity.
#     Returns top_n closest matches as a list of (query_id, query_text, similarity).
#     """
#     user_vec = vectorizer.transform([user_text])
#     sims     = cosine_similarity(user_vec, tfidf_matrix).flatten()
#     top_idx  = sims.argsort()[::-1][:top_n]
# 
#     results = []
#     for idx in top_idx:
#         results.append({
#             "query_id":   query_map.iloc[idx]["query_id"],
#             "query_text": query_map.iloc[idx]["query"],
#             "similarity": sims[idx],
#         })
#     return results
# 
# 
# # ── Load ──────────────────────────────────────────────────────────────────────
# with st.spinner("⏳ Training models on first run — please wait…"):
#     df, feat_cols, xgb_m, lgb_m, query_map, vectorizer, tfidf_matrix = load_and_train()
# 
# # ── UI ────────────────────────────────────────────────────────────────────────
# st.title("🔍 Product Search Ranking")
# st.caption("Type anything — the engine finds the closest matching query in the dataset")
# st.markdown("---")
# 
# # Free text input
# user_query = st.text_input(
#     "🔎 Type your search query:",
#     placeholder="e.g.  bulb,  short a-line skirt,  wireless headphones …"
# )
# 
# col1, col2 = st.columns([3, 1])
# with col1:
#     top_k = st.slider("Number of results", 5, 30, 10)
# with col2:
#     model_choice = st.radio("Model", ["XGBoost", "LightGBM"], horizontal=True)
# 
# model = xgb_m if model_choice == "XGBoost" else lgb_m
# 
# # ── Search ────────────────────────────────────────────────────────────────────
# if user_query.strip():
#     matches = find_best_matching_query(user_query, vectorizer, tfidf_matrix, query_map, top_n=5)
#     best    = matches[0]
# 
#     # Show what query was matched
#     st.markdown(f"""
#     <div class="matched-query">
#         🎯 <b>Matched dataset query:</b> "{best['query_text']}"
#         &nbsp;&nbsp;
#         <span style="color:#666;font-size:0.8rem;">(similarity: {best['similarity']:.2f})</span>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # Let user pick a different match if top result isn't right
#     if matches[1]["similarity"] > 0:
#         with st.expander("🔄 Not what you meant? Pick a closer match"):
#             for m in matches:
#                 if st.button(f"📌 {m['query_text']}  ({m['similarity']:.2f})", key=m["query_id"]):
#                     best = m
# 
#     # Rank products for matched query
#     selected_qid = best["query_id"]
#     subset = df[df["query_id"] == selected_qid].copy()
#     subset["score"] = model.predict(subset[feat_cols].values)
#     subset = subset.sort_values("score", ascending=False).reset_index(drop=True)
# 
#     rel_class = {3: "rel-3", 2: "rel-2", 1: "rel-1", 0: "rel-0"}
# 
#     st.markdown(f"### Results ({len(subset)} products · showing top {top_k})")
# 
#     for i, row in subset.head(top_k).iterrows():
#         rank_num  = i + 1
#         pid       = row["product_id"]
#         rel       = int(row["relevance"])
#         rel_label = row["relevance_label"]
#         score     = row["score"]
#         rc        = rel_class.get(rel, "rel-0")
#         amazon_url = f"https://www.amazon.com/dp/{pid}"
# 
#         st.markdown(f"""
#         <div class="result-card">
#             <span class="rank-badge">#{rank_num}</span>
#             &nbsp;&nbsp;
#             <span class="relevance-label {rc}">{rel_label}</span>
#             &nbsp;&nbsp;
#             <a href="{amazon_url}" target="_blank" style="color:#4a9eff;font-size:0.9rem;">
#                 🛒 View on Amazon →
#             </a>
#             <br/>
#             <span class="product-id">Product ID: {pid}</span>
#             &nbsp;·&nbsp;
#             <span style="color:#666;font-size:0.8rem;">Score: {score:.4f}</span>
#         </div>
#         """, unsafe_allow_html=True)
# 
# else:
#     st.info("👆 Type any product search query above to get started")







